### ISSUE TITLE
Tesla Coil breaks when meeting a modded item with a new collider

### ISSUE THREAD

**Issue by Aspa102** [studio-minus/ppg-bug-reports#9]
Bug:
Tesla coils break if a modded item with fixcolliders ran enters its radius. Debug logs says the collider cannot be null, despite the collider existing.

Reproduction:
Literally just grab a random modded item with a different collider and put it inside the radius of a tesla coil which is active.

Mods:
OCM - Doesn't touch the tesla coil, plus it's literally just my own mod. (Tested without this mod active, bug still occurs)
Lightsabers - Enabled to check if the bug happened with other mods.

System Information:
 - Operating system: Windows 10
 - Game version: 1.18 Pre1
 - GPU: Intel UHD 620
 - CPU: Intel Core i7 8550U (God save my soul)

**Comment by mestiez** [comment]
This made me check the Tesla coil behaviours and the code I wrote there is deplorable. I have rewritten it. 
This bug probably happens because a completely undocumented and unmentioned method should be called after the object colliders change: `PhysicalBehaviours.ResetColliderArray();` Though this doesn't explain why it happens after `FixColliders()` is called, since that method will also reset the array.

Anyway, he `colliders` array is more or less a remnant of how things used to work and is only used by a few systems in the game. Ideally it should be removed. For now though, this bug has been fixed.
